### ISSUE TITLE
SFB crash in AudioRingBuffer.cpp

### ISSUE THREAD

**Issue by woc2006** [sbooth/SFBAudioEngine#61] opened 2015-11-16 14:42 UTC
function: StoreABL
org.sbooth.AudioEngine.Decoder (26): EXC_BAD_ACCESS(code=1, address=0x7edf000)

Variables:
![image](https://cloud.githubusercontent.com/assets/1716430/11184524/2a334afe-8cb3-11e5-92d2-76cf3c45357d.png)

**Comment by woc2006** [comment] 2015-11-16 14:43
Stack:
![image](https://cloud.githubusercontent.com/assets/1716430/11184550/548ebf0e-8cb3-11e5-8015-4bfd3e1b3065.png)

Environment:
XCode 7.1 with iOS 9.1 (iPhone 5)

**Comment by sbooth** [comment] 2015-11-17 02:36
Is this crash reproducible?  If so, do you have a sample project illustrating the problem?

**Comment by woc2006** [comment] 2015-11-17 02:40
Not reproducible, I tried for 5 times.

**Comment by sbooth** [comment] 2015-11-17 02:50
Thanks.  It looks like `buffers` may have been corrupted somehow but it's hard to say for certain.  I will close this for now but please reopen the issue if it happens again.

**Closed by sbooth** 2015-11-17 02:50 UTC

**Comment by woc2006** [comment] 2015-11-21 15:16
I managed to write a demo about the bug, 
https://www.dropbox.com/s/muv2awxodpyl0c9/demo.zip?dl=0

call the demo in your code like:
```cpp
int ret = -1;
void init(){
    auto instance = SimpleManager::getInstance();
    ret = instance->prepare("hit-1.ogg");
}

//call the function multi times per 1/60 second
void playSound(){
    SimpleManager::getInstance()->play(ret);
}
```

**Comment by sbooth** [comment] 2015-11-21 18:26
Thanks for the sample code.  Is `playSound()` called from the same thread every time?  I noticed that `SimpleManager` doesn't perform any synchronization on the static variables `audios` and `players` so I wonder if that could be related.

**Comment by woc2006** [comment] 2015-11-22 02:30
I called playSound in the same thread of SFB.
