### ISSUE TITLE
arm64 architecture support 

### ISSUE THREAD

**Issue by xinyu198736** [sbooth/SFBAudioEngine#94] opened 2020-04-17 09:35 UTC
hello，the download lib does not include the arm64 architecture library，can‘t use in the new ios device

**Comment by sbooth** [comment] 2020-05-01 15:50
Related to #93

**Comment by sbooth** [comment] 2020-05-01 15:51
Duplicate of #50

**Closed by sbooth** 2020-05-01 15:51 UTC

**Comment by xinyu198736** [comment] 2020-05-07 13:38
thank you very much
